const Data = [
    {
        id: 101,
        image: "assets/image1.jpg",
        title: "Luxury Apartment in Delhi",
        description: "A spacious 3BHK apartment in the heart of Delhi with modern amenities.",
        price: 55000,
        city: "Delhi",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 110000,
        address: "Connaught Place, Delhi",
        landmark: "Near Rajiv Chowk Metro Station",
        overlooking: "Park",
        developer: "DLF Group",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 102,
        image: "assets/image3.jpg",
        title: "2BHK Apartment near Connaught Place",
        description: "Cozy 2BHK near Delhi's prime commercial area.",
        price: 45000,
        city: "Delhi",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 90000,
        address: "Connaught Place, Delhi",
        landmark: "Near Palika Bazar",
        overlooking: "Garden",
        developer: "Ansal API",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 103,
        image: "assets/image2.jpg",
        title: "3BHK Apartment in South Delhi",
        description: "Spacious apartment with balcony views in South Delhi.",
        price: 60000,
        city: "Delhi",
        bhk: "3BHK",
        flatSize: 1600,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 120000,
        address: "South Extension, Delhi",
        landmark: "Near AIIMS Hospital",
        overlooking: "Park",
        developer: "Unitech Group",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 104,
        image: "assets/image7.jpg",
        title: "Penthouse in Dwarka",
        description: "Luxurious penthouse with a rooftop garden.",
        price: 90000,
        city: "Delhi",
        bhk: "3BHK",
        flatSize: 2000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "7th",
        balconies: 3,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 180000,
        address: "Dwarka, Delhi",
        landmark: "Near Sector 9 Metro Station",
        overlooking: "Garden",
        developer: "Godrej Properties",
        facing: "South",
        lift: "Yes"
    },
    {
        id: 105,
        image: "assets/image9.jpg",
        title: "1BHK Studio in Hauz Khas",
        description: "Modern studio apartment with access to local nightlife.",
        price: 35000,
        city: "Delhi",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 70000,
        address: "Hauz Khas, Delhi",
        landmark: "Near Hauz Khas Village",
        overlooking: "Garden",
        developer: "Tata Housing",
        facing: "East",
        lift: "No"
    },
    {
        id: 106,
        image: "assets/image10.jpg",
        title: "2BHK Apartment in Noida",
        description: "Modern 2BHK apartment in Noida, a part of Delhi NCR.",
        price: 40000,
        city: "Delhi",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 80000,
        address: "Sector 18, Noida",
        landmark: "Near Atta Market",
        overlooking: "Park",
        developer: "Mahagun",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 107,
        image: "assets/image1.jpg",
        title: "3BHK Flat in Rohini",
        description: "Spacious 3BHK flat with park views in Rohini.",
        price: 48000,
        city: "Delhi",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 96000,
        address: "Sector 16, Rohini, Delhi",
        landmark: "Near Metro Walk Mall",
        overlooking: "Park",
        developer: "Supertech",
        facing: "North",
        lift: "Yes"
    },

    // Mumbai (7 properties)
    {
        id: 201,
        image: "assets/image10.jpg",
        title: "2BHK Sea-facing Apartment in Mumbai",
        description: "A cozy 2BHK apartment with a stunning sea view.",
        price: 80000,
        city: "Mumbai",
        bhk: "2BHK",
        flatSize: 1300,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "10th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 160000,
        address: "Juhu, Mumbai",
        landmark: "Near Juhu Beach",
        overlooking: "Sea",
        developer: "Lodha Group",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 202,
        image: "assets/image5.jpg",
        title: "3BHK Apartment in Andheri",
        description: "Spacious 3BHK in Mumbai's bustling Andheri area.",
        price: 70000,
        city: "Mumbai",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "6th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 140000,
        address: "Andheri West, Mumbai",
        landmark: "Near Andheri Metro Station",
        overlooking: "City",
        developer: "Oberoi Realty",
        facing: "South",
        lift: "Yes"
    },
    {
        id: 203,
        image: "assets/image2.jpg",
        title: "1BHK Studio in Bandra",
        description: "Modern 1BHK studio located near Mumbai's Bandstand.",
        price: 45000,
        city: "Mumbai",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "3rd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 90000,
        address: "Bandra, Mumbai",
        landmark: "Near Bandra Bandstand",
        overlooking: "Garden",
        developer: "Raheja Corp",
        facing: "East",
        lift: "No"
    },
    {
        id: 204,
        image: "assets/image4.jpg",
        title: "4BHK Penthouse in Powai",
        description: "Exclusive 4BHK penthouse with panoramic views of Powai Lake.",
        price: 120000,
        city: "Mumbai",
        bhk: "4BHK",
        flatSize: 2500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "12th",
        balconies: 3,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 240000,
        address: "Powai, Mumbai",
        landmark: "Near Hiranandani Gardens",
        overlooking: "Lake",
        developer: "Hiranandani Group",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 205,
        image: "assets/image6.jpg",
        title: "3BHK Flat in Navi Mumbai",
        description: "A spacious flat in a quiet Navi Mumbai neighborhood.",
        price: 60000,
        city: "Mumbai",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 120000,
        address: "Nerul, Navi Mumbai",
        landmark: "Near Palm Beach Road",
        overlooking: "City",
        developer: "Godrej Properties",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 206,
        image: "assets/image8.jpg",
        title: "2BHK Apartment in Dadar",
        description: "Modern 2BHK with easy access to local transport.",
        price: 65000,
        city: "Mumbai",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 130000,
        address: "Dadar, Mumbai",
        landmark: "Near Dadar Railway Station",
        overlooking: "City",
        developer: "L&T Realty",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 207,
        image: "assets/image9.jpg",
        title: "3BHK Apartment in Malad",
        description: "Spacious apartment in a prime location.",
        price: 75000,
        city: "Mumbai",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "9th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 150000,
        address: "Malad West, Mumbai",
        landmark: "Near Infinity Mall",
        overlooking: "City",
        developer: "Mahindra Lifespace",
        facing: "North",
        lift: "Yes"
    },

    // Pune (7 properties)
    {
        id: 301,
        image: "assets/image7.jpg",
        title: "1BHK Studio in Hinjewadi",
        description: "Perfect studio apartment for IT professionals in Hinjewadi.",
        price: 35000,
        city: "Pune",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 70000,
        address: "Hinjewadi, Pune",
        landmark: "Near Rajiv Gandhi IT Park",
        overlooking: "Garden",
        developer: "Kolte Patil",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 302,
        image: "assets/image8.jpg",
        title: "2BHK Flat in Kalyani Nagar",
        description: "A modern 2BHK in Pune's upscale Kalyani Nagar.",
        price: 45000,
        city: "Pune",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 90000,
        address: "Kalyani Nagar, Pune",
        landmark: "Near Bishop's School",
        overlooking: "Park",
        developer: "Marvel Realtors",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 303,
        image: "assets/image1.jpg",
        title: "3BHK Flat in Baner",
        description: "A premium 3BHK flat in Pune's Baner area.",
        price: 55000,
        city: "Pune",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 2,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 110000,
        address: "Baner, Pune",
        landmark: "Near Balewadi High Street",
        overlooking: "Park",
        developer: "Rohan Builders",
        facing: "South",
        lift: "Yes"
    },
    {
        id: 304,
        image: "assets/image6.jpg",
        title: "2BHK Apartment in Viman Nagar",
        description: "Cozy 2BHK with great connectivity to the airport.",
        price: 40000,
        city: "Pune",
        bhk: "2BHK",
        flatSize: 1100,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 80000,
        address: "Viman Nagar, Pune",
        landmark: "Near Pune International Airport",
        overlooking: "City",
        developer: "Goel Ganga Group",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 305,
        image: "assets/image4.jpg",
        title: "4BHK Villa in Koregaon Park",
        description: "A luxurious 4BHK villa with a private garden.",
        price: 120000,
        city: "Pune",
        bhk: "4BHK",
        flatSize: 3500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 240000,
        address: "Koregaon Park, Pune",
        landmark: "Near Osho Ashram",
        overlooking: "Garden",
        developer: "Panchshil Realty",
        facing: "East",
        lift: "No"
    },
    {
        id: 306,
        image: "assets/image9.jpg",
        title: "3BHK Penthouse in Aundh",
        description: "Penthouse with a large terrace in Aundh.",
        price: 85000,
        city: "Pune",
        bhk: "3BHK",
        flatSize: 2000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "10th",
        balconies: 3,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 170000,
        address: "Aundh, Pune",
        landmark: "Near Parihar Chowk",
        overlooking: "City",
        developer: "VTP Realty",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 307,
        image: "assets/image5.jpg",
        title: "2BHK Flat in Bavdhan",
        description: "Spacious 2BHK with a balcony in Bavdhan.",
        price: 42000,
        city: "Pune",
        bhk: "2BHK",
        flatSize: 1250,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 84000,
        address: "Bavdhan, Pune",
        landmark: "Near Chandani Chowk",
        overlooking: "Hill",
        developer: "Paranjape Schemes",
        facing: "North",
        lift: "Yes"
    },
    // Bangalore (7 properties)
    {
        id: 401,
        image: "assets/image3.jpg",
        title: "2BHK Apartment in Koramangala",
        description: "Modern 2BHK in Bangalore's trendy Koramangala.",
        price: 50000,
        securityDeposit: 150000,
        address: "123, 4th Block, Koramangala, Bangalore",
        landmark: "Near Forum Mall",
        overlooking: "Garden",
        developer: "Prestige",
        facing: "East",
        lift: true,
        city: "Bangalore",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "1 Car",
        type: 'flat'
    },
    {
        id: 402,
        image: "assets/image1.jpg",
        title: "1BHK Studio in Indiranagar",
        description: "A cozy 1BHK studio in one of Bangalore's prime locations.",
        price: 45000,
        securityDeposit: 135000,
        address: "56, 100 Feet Road, Indiranagar, Bangalore",
        landmark: "Opposite Toobler Cafe",
        overlooking: "Park",
        developer: "Sobha",
        facing: "West",
        lift: true,
        city: "Bangalore",
        bhk: "1BHK",
        flatSize: 550,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: 'flat'
    },
    {
        id: 403,
        image: "assets/image4.jpg",
        title: "4BHK Villa in Sarjapur",
        description: "Luxurious 4BHK villa in a gated community with private pool.",
        price: 150000,
        securityDeposit: 450000,
        address: "Sarjapur Main Road, Bangalore",
        landmark: "Near Wipro Office",
        overlooking: "Garden",
        developer: "Brigade",
        facing: "North",
        lift: false,
        city: "Bangalore",
        bhk: "4BHK",
        flatSize: 3000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground + 1",
        balconies: 4,
        carParking: "3 Cars",
        type: 'villa'
    },
    {
        id: 404,
        image: "assets/image5.jpg",
        title: "3BHK Flat in Hebbal",
        description: "Spacious 3BHK flat with lake views in Hebbal.",
        price: 70000,
        securityDeposit: 210000,
        address: "Hebbal Ring Road, Bangalore",
        landmark: "Near Hebbal Lake",
        overlooking: "Lake",
        developer: "L&T",
        facing: "South",
        lift: true,
        city: "Bangalore",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "6th",
        balconies: 2,
        carParking: "1 Car",
        type: 'flat'
    },
    {
        id: 405,
        image: "assets/image2.jpg",
        title: "2BHK Apartment in Jayanagar",
        description: "Lovely 2BHK apartment with garden views.",
        price: 48000,
        securityDeposit: 144000,
        address: "9th Block, Jayanagar, Bangalore",
        landmark: "Near Jayanagar 4th Block Complex",
        overlooking: "Park",
        developer: "Puravankara",
        facing: "East",
        lift: true,
        city: "Bangalore",
        bhk: "2BHK",
        flatSize: 1100,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: 'flat'
    },
    {
        id: 406,
        image: "assets/image6.jpg",
        title: "1BHK Apartment in Whitefield",
        description: "1BHK apartment close to IT parks.",
        price: 40000,
        securityDeposit: 120000,
        address: "ITPL Road, Whitefield, Bangalore",
        landmark: "Near ITPL",
        overlooking: "City",
        developer: "Sobha",
        facing: "North",
        lift: true,
        city: "Bangalore",
        bhk: "1BHK",
        flatSize: 650,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "4th",
        balconies: 1,
        carParking: "No Parking",
        type: 'flat'
    },
    {
        id: 407,
        image: "assets/image7.jpg",
        title: "5BHK Luxurious Villa in Devanahalli",
        description: "Spacious 5BHK villa with large outdoor spaces.",
        price: 180000,
        securityDeposit: 540000,
        address: "Devanahalli Road, Bangalore",
        landmark: "Near Bangalore International Airport",
        overlooking: "Garden",
        developer: "Prestige",
        facing: "West",
        lift: false,
        city: "Bangalore",
        bhk: "5BHK",
        flatSize: 4000,
        furnishing: "Fully Furnished",
        bathrooms: 5,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "4 Cars",
        type: 'villa'
    },

    // Raipur (7 properties)
    {
        id: 501,
        image: "assets/image8.jpg",
        title: "2BHK Apartment in Raipur",
        description: "Well-located 2BHK apartment in the city center.",
        price: 20000,
        securityDeposit: 60000,
        address: "Civil Lines, Raipur",
        landmark: "Near Raipur Junction",
        overlooking: "City",
        developer: "Avinash Builders",
        facing: "East",
        lift: true,
        city: "Raipur",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat"
    },
    {
        id: 502,
        image: "assets/image9.jpg",
        title: "1BHK Studio in Shankar Nagar",
        description: "Compact 1BHK studio with modern amenities.",
        price: 15000,
        city: "Raipur",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Home",
        securityDeposit: 30000,
        address: "Shankar Nagar, Raipur",
        landmark: "Near Shankar Park",
        overlooking: "Park",
        developer: "Shankar Developers",
        facing: "East",
        lift: "No"
    },
    {
        id: 503,
        image: "assets/image10.jpg",
        title: "3BHK Flat in VIP Road",
        description: "Spacious 3BHK flat near schools and markets.",
        price: 30000,
        city: "Raipur",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 90000,
        address: "VIP Road, Raipur",
        landmark: "Near VIP School",
        overlooking: "Garden",
        developer: "VIP Builders",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 504,
        image: "assets/image5.jpg",
        title: "4BHK Villa in Raipur",
        description: "Luxurious villa with a garden in a peaceful locality.",
        price: 70000,
        city: "Raipur",
        bhk: "4BHK",
        flatSize: 2500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "2 Cars",
        type: "Villa",
        securityDeposit: 210000,
        address: "Green Park, Raipur",
        landmark: "Near City Garden",
        overlooking: "Park",
        developer: "Green Park Developers",
        facing: "West",
        lift: "No"
    },
    {
        id: 505,
        image: "assets/image4.jpg",
        title: "1BHK Flat in Mowa",
        description: "1BHK flat in a vibrant neighborhood.",
        price: 16000,
        city: "Raipur",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 32000,
        address: "Mowa, Raipur",
        landmark: "Near Mowa Market",
        overlooking: "Street",
        developer: "Mowa Builders",
        facing: "South",
        lift: "Yes"
    },
    {
        id: 506,
        image: "assets/image9.jpg",
        title: "3BHK Apartment in Ganjpara",
        description: "Modern 3BHK apartment with balcony views.",
        price: 35000,
        city: "Raipur",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 105000,
        address: "Ganjpara, Raipur",
        landmark: "Near Ganjpara Market",
        overlooking: "Garden",
        developer: "Ganjpara Developers",
        facing: "North-East",
        lift: "Yes"
    },
    {
        id: 507,
        image: "assets/image3.jpg",
        title: "2BHK Flat in Ratanpur",
        description: "2BHK flat with great connectivity to major roads.",
        price: 22000,
        city: "Raipur",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 66000,
        address: "Ratanpur, Raipur",
        landmark: "Near Ratanpur Junction",
        overlooking: "Street",
        developer: "Ratan Builders",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 601,
        image: "assets/image1.jpg",
        title: "3BHK Apartment in Bhopal",
        description: "Modern 3BHK apartment with city views.",
        price: 35000,
        city: "Bhopal",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 105000,
        address: "Arera Hills, Bhopal",
        landmark: "Near City Mall",
        overlooking: "City View",
        developer: "Arera Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 602,
        image: "assets/image2.jpg",
        title: "2BHK Flat near Bhopal Lake",
        description: "Scenic views from this cozy 2BHK.",
        price: 28000,
        city: "Bhopal",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 84000,
        address: "Bhopal Lake Road, Bhopal",
        landmark: "Near Bhopal Lake",
        overlooking: "Lake",
        developer: "Lakeview Developers",
        facing: "North",
        lift: "No"
    },
    {
        id: 603,
        image: "assets/image3.jpg",
        title: "1BHK Studio in Habibganj",
        description: "Compact studio apartment for young professionals.",
        price: 15000,
        city: "Bhopal",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 30000,
        address: "Habibganj, Bhopal",
        landmark: "Near Habibganj Railway Station",
        overlooking: "Street",
        developer: "Habib Developers",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 604,
        image: "assets/image4.jpg",
        title: "4BHK Villa in Arera Colony",
        description: "Luxurious villa with a private garden.",
        price: 70000,
        city: "Bhopal",
        bhk: "4BHK",
        flatSize: 3000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "2 Cars",
        type: "Villa",
        securityDeposit: 210000,
        address: "Arera Colony, Bhopal",
        landmark: "Near Arera Park",
        overlooking: "Park",
        developer: "Arera Developers",
        facing: "South-East",
        lift: "No"
    },
    {
        id: 605,
        image: "assets/image5.jpg",
        title: "2BHK Flat in Shahpura",
        description: "Cozy flat in a peaceful neighborhood.",
        price: 22000,
        city: "Bhopal",
        bhk: "2BHK",
        flatSize: 900,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 66000,
        address: "Shahpura, Bhopal",
        landmark: "Near Shahpura Lake",
        overlooking: "Park",
        developer: "Shahpura Developers",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 606,
        image: "assets/image6.jpg",
        title: "3BHK Apartment in MP Nagar",
        description: "Modern amenities in the heart of the city.",
        price: 40000,
        city: "Bhopal",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 120000,
        address: "MP Nagar, Bhopal",
        landmark: "Near DB Mall",
        overlooking: "City View",
        developer: "MP Nagar Developers",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 607,
        image: "assets/image7.jpg",
        title: "3BHK Flat in Banjara Hills",
        description: "Luxury living in Hyderabad's upscale area.",
        price: 80000,
        city: "Hyderabad",
        bhk: "3BHK",
        flatSize: 1800,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "6th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 240000,
        address: "Banjara Hills, Hyderabad",
        landmark: "Near Banjara Park",
        overlooking: "Garden",
        developer: "Banjara Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 608,
        image: "assets/image8.jpg",
        title: "2BHK Apartment in Gachibowli",
        description: "Spacious apartment near IT hubs.",
        price: 60000,
        city: "Hyderabad",
        bhk: "2BHK",
        flatSize: 1300,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Bachelors",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 180000,
        address: "Gachibowli, Hyderabad",
        landmark: "Near DLF Building",
        overlooking: "City View",
        developer: "Gachibowli Builders",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 609,
        image: "assets/image9.jpg",
        title: "1BHK Studio in Kukatpally",
        description: "Ideal for working professionals.",
        price: 30000,
        city: "Hyderabad",
        bhk: "1BHK",
        flatSize: 700,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 90000,
        address: "Kukatpally, Hyderabad",
        landmark: "Near Kukatpally Metro",
        overlooking: "Street",
        developer: "Kukatpally Developers",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 610,
        image: "assets/image10.jpg",
        title: "4BHK Villa in Jubilee Hills",
        description: "Elegant villa with modern amenities.",
        price: 150000,
        city: "Hyderabad",
        bhk: "4BHK",
        flatSize: 3500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 450000,
        address: "Jubilee Hills, Hyderabad",
        landmark: "Near Jubilee Hills Check Post",
        overlooking: "Garden",
        developer: "Jubilee Developers",
        facing: "South",
        lift: "No"
    },
    {
        id: 611,
        image: "assets/image7.jpg",
        title: "2BHK Flat in Hi-Tech City",
        description: "Modern living in a vibrant area.",
        price: 50000,
        city: "Hyderabad",
        bhk: "2BHK",
        flatSize: 1100,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 150000,
        address: "Hi-Tech City, Hyderabad",
        landmark: "Near Shilparamam",
        overlooking: "City View",
        developer: "Hi-Tech Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 612,
        image: "assets/image2.jpg",
        title: "3BHK Apartment in Banjara Hills",
        description: "Luxurious apartment with great amenities.",
        price: 70000,
        city: "Hyderabad",
        bhk: "3BHK",
        flatSize: 1600,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Flat",
        securityDeposit: 210000,
        address: "Banjara Hills, Hyderabad",
        landmark: "Near LV Prasad Eye Institute",
        overlooking: "Park",
        developer: "Banjara Builders",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 613,
        image: "assets/image10.jpg",
        title: "3BHK Flat in Sector 17",
        description: "Beautiful flat in the heart of Chandigarh.",
        price: 50000,
        city: "Chandigarh",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 150000,
        address: "Sector 17, Chandigarh",
        landmark: "Near Rose Garden",
        overlooking: "City View",
        developer: "Sector Developers",
        facing: "North-East",
        lift: "Yes"
    },
    {
        id: 614,
        image: "assets/image1.jpg",
        title: "2BHK Apartment in Mohali",
        description: "Modern apartment with easy access to amenities.",
        price: 30000,
        city: "Chandigarh",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 90000,
        address: "Mohali, Chandigarh",
        landmark: "Near Mohali Stadium",
        overlooking: "Street",
        developer: "Mohali Builders",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 615,
        image: "assets/image9.jpg",
        title: "1BHK Studio in Chandigarh",
        description: "Compact and stylish studio for professionals.",
        price: 18000,
        city: "Chandigarh",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "3rd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 54000,
        address: "Sector 20, Chandigarh",
        landmark: "Near Sector 20 Market",
        overlooking: "Street",
        developer: "Chandigarh Builders",
        facing: "North",
        lift: "No"
    },
    {
        id: 616,
        image: "assets/image1.jpg",
        title: "4BHK Villa in Panchkula",
        description: "Spacious villa with a private garden.",
        price: 85000,
        city: "Chandigarh",
        bhk: "4BHK",
        flatSize: 2800,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 2,
        carParking: "2 Cars",
        type: "Villa",
        securityDeposit: 255000,
        address: "Panchkula, Chandigarh",
        landmark: "Near Panchkula Golf Course",
        overlooking: "Garden",
        developer: "Panchkula Developers",
        facing: "South-East",
        lift: "No"
    },

    {
        id: 701,
        image: "assets/image7.jpg",
        title: "2BHK Flat in Sector 18",
        description: "Spacious 2BHK with excellent connectivity.",
        price: 35000,
        city: "Noida",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 105000,
        address: "Sector 18, Noida",
        landmark: "Near Noida Metro Station",
        overlooking: "Park",
        developer: "Noida Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 702,
        image: "assets/image8.jpg",
        title: "3BHK Apartment in Sector 62",
        description: "Modern 3BHK in IT hub with great amenities.",
        price: 50000,
        city: "Noida",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Bachelors",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 150000,
        address: "Sector 62, Noida",
        landmark: "Near IT Park",
        overlooking: "City View",
        developer: "ABC Builders",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 703,
        image: "assets/image9.jpg",
        title: "1BHK Studio in Sector 76",
        description: "Cozy studio for working professionals.",
        price: 18000,
        city: "Noida",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 54000,
        address: "Sector 76, Noida",
        landmark: "Near Supertech Capetown",
        overlooking: "Street",
        developer: "Supertech Developers",
        facing: "South",
        lift: "No"
    },
    {
        id: 704,
        image: "assets/image10.jpg",
        title: "4BHK Villa in Sector 128",
        description: "Luxury villa in Noida with a private garden.",
        price: 120000,
        city: "Noida",
        bhk: "4BHK",
        flatSize: 3000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 360000,
        address: "Sector 128, Noida",
        landmark: "Near Jaypee Greens",
        overlooking: "Garden",
        developer: "Jaypee Builders",
        facing: "West",
        lift: "No"
    },
    {
        id: 705,
        image: "assets/image1.jpg",
        title: "2BHK Apartment in Sector 50",
        description: "Beautiful 2BHK in a posh area.",
        price: 40000,
        city: "Noida",
        bhk: "2BHK",
        flatSize: 1400,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 120000,
        address: "Sector 50, Noida",
        landmark: "Near Sector 50 Market",
        overlooking: "Park",
        developer: "Sector Developers",
        facing: "North-East",
        lift: "Yes"
    },
    {
        id: 706,
        image: "assets/image2.jpg",
        title: "3BHK Penthouse in Sector 78",
        description: "Luxury penthouse with panoramic city views.",
        price: 75000,
        city: "Noida",
        bhk: "3BHK",
        flatSize: 2000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "8th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Penthouse",
        securityDeposit: 225000,
        address: "Sector 78, Noida",
        landmark: "Near Metro Station",
        overlooking: "City View",
        developer: "Noida Penthouse Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 707,
        image: "assets/image3.jpg",
        title: "1BHK Flat in Sector 34",
        description: "Compact and affordable flat for singles.",
        price: 20000,
        city: "Noida",
        bhk: "1BHK",
        flatSize: 700,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 60000,
        address: "Sector 34, Noida",
        landmark: "Near Noida City Centre",
        overlooking: "Street",
        developer: "Sector Developers",
        facing: "North",
        lift: "No"
    },
    {
        id: 801,
        image: "assets/image4.jpg",
        title: "2BHK Flat in Civil Lines",
        description: "Spacious 2BHK with premium facilities.",
        price: 25000,
        city: "Prayagraj",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 75000,
        address: "Civil Lines, Prayagraj",
        landmark: "Near Sangam Hall",
        overlooking: "Park",
        developer: "Civil Lines Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 802,
        image: "assets/image5.jpg",
        title: "3BHK Apartment in Tagore Town",
        description: "Elegant 3BHK with modern amenities.",
        price: 35000,
        city: "Prayagraj",
        bhk: "3BHK",
        flatSize: 1600,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 105000,
        address: "Tagore Town, Prayagraj",
        landmark: "Near Tagore Park",
        overlooking: "Street",
        developer: "Tagore Town Developers",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 803,
        image: "assets/image6.jpg",
        title: "1BHK Studio in Katra",
        description: "Compact and affordable studio apartment.",
        price: 15000,
        city: "Prayagraj",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 45000,
        address: "Katra, Prayagraj",
        landmark: "Near Allahabad University",
        overlooking: "Street",
        developer: "Katra Builders",
        facing: "South",
        lift: "No"
    },
    {
        id: 804,
        image: "assets/image7.jpg",
        title: "4BHK Villa in Ashok Nagar",
        description: "Luxurious 4BHK villa with a garden.",
        price: 85000,
        city: "Prayagraj",
        bhk: "4BHK",
        flatSize: 3000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 255000,
        address: "Ashok Nagar, Prayagraj",
        landmark: "Near Ashok Park",
        overlooking: "Garden",
        developer: "Ashok Developers",
        facing: "West",
        lift: "No"
    },
    {
        id: 805,
        image: "assets/image9.jpg",
        title: "2BHK Apartment in George Town",
        description: "Modern 2BHK apartment in a prime location.",
        price: 28000,
        city: "Prayagraj",
        bhk: "2BHK",
        flatSize: 1100,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 84000,
        address: "George Town, Prayagraj",
        landmark: "Near George Town Market",
        overlooking: "Street",
        developer: "George Builders",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 806,
        image: "assets/image10.jpg",
        title: "3BHK Apartment in Lukerganj",
        description: "Spacious 3BHK apartment with premium amenities.",
        price: 32000,
        city: "Prayagraj",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 96000,
        address: "Lukerganj, Prayagraj",
        landmark: "Near Lukerganj Club",
        overlooking: "Park",
        developer: "Lukerganj Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 807,
        image: "assets/image7.jpg",
        title: "1BHK Flat in Rajapur",
        description: "Compact flat ideal for singles or couples.",
        price: 16000,
        city: "Prayagraj",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Semi - Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 48000,
        address: "Rajapur, Prayagraj",
        landmark: "Near Rajapur Market",
        overlooking: "Street",
        developer: "Rajapur Builders",
        facing: "South",
        lift: "No"
    },

    {
        id: 901,
        image: "assets/image8.jpg",
        title: "2BHK Flat in Swaroop Nagar",
        description: "Spacious 2BHK flat in a premium location.",
        price: 28000,
        city: "Kanpur",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 84000,
        address: "Swaroop Nagar, Kanpur",
        landmark: "Near Swaroop Park",
        overlooking: "Park",
        developer: "Kanpur Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 902,
        image: "assets/image6.jpg",
        title: "3BHK Apartment in Civil Lines",
        description: "Elegant 3BHK apartment with modern amenities.",
        price: 35000,
        city: "Kanpur",
        bhk: "3BHK",
        flatSize: 1600,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 105000,
        address: "Civil Lines, Kanpur",
        landmark: "Near Civil Lines Park",
        overlooking: "City View",
        developer: "Civil Builders",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 903,
        image: "assets/image10.jpg",
        title: "1BHK Studio in Kakadeo",
        description: "Compact studio for professionals.",
        price: 15000,
        city: "Kanpur",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 45000,
        address: "Kakadeo, Kanpur",
        landmark: "Near Kakadeo Market",
        overlooking: "Street",
        developer: "Kakadeo Builders",
        facing: "South",
        lift: "No"
    },
    {
        id: 904,
        image: "assets/image2.jpg",
        title: "4BHK Villa in Kalyanpur",
        description: "Luxury villa with a private garden.",
        price: 90000,
        city: "Kanpur",
        bhk: "4BHK",
        flatSize: 3000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 270000,
        address: "Kalyanpur, Kanpur",
        landmark: "Near Kalyanpur Park",
        overlooking: "Garden",
        developer: "Kalyanpur Developers",
        facing: "West",
        lift: "No"
    },
    {
        id: 905,
        image: "assets/image3.jpg",
        title: "2BHK Apartment in Govind Nagar",
        description: "Spacious 2BHK apartment with modern facilities.",
        price: 26000,
        city: "Kanpur",
        bhk: "2BHK",
        flatSize: 1100,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 78000,
        address: "Govind Nagar, Kanpur",
        landmark: "Near Govind Park",
        overlooking: "Street",
        developer: "Govind Builders",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 906,
        image: "assets/image1.jpg",
        title: "3BHK Penthouse in Shyam Nagar",
        description: "Luxurious penthouse with panoramic city views.",
        price: 75000,
        city: "Kanpur",
        bhk: "3BHK",
        flatSize: 2000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "8th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Penthouse",
        securityDeposit: 225000,
        address: "Shyam Nagar, Kanpur",
        landmark: "Near Shyam Nagar Metro",
        overlooking: "City View",
        developer: "Shyam Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 907,
        image: "assets/image5.jpg",
        title: "1BHK Flat in Panki",
        description: "Affordable 1BHK flat for singles.",
        price: 18000,
        city: "Kanpur",
        bhk: "1BHK",
        flatSize: 700,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 54000,
        address: "Panki, Kanpur",
        landmark: "Near Panki Temple",
        overlooking: "Street",
        developer: "Panki Builders",
        facing: "North",
        lift: "No"
    },
    {
        id: 1001,
        image: "assets/image10.jpg",
        title: "2BHK Flat in Patna",
        description: "Spacious 2BHK in the heart of Patna.",
        price: 22000,
        city: "Patna",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 66000,
        address: "Fraser Road, Patna",
        landmark: "Near Gandhi Maidan",
        overlooking: "Park",
        developer: "Patna Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 1002,
        image: "assets/image9.jpg",
        title: "3BHK Apartment in Kankarbagh",
        description: "Modern 3BHK apartment in a prime location.",
        price: 30000,
        city: "Patna",
        bhk: "3BHK",
        flatSize: 1400,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 90000,
        address: "Kankarbagh, Patna",
        landmark: "Near Kankarbagh Market",
        overlooking: "City View",
        developer: "Bihar Developers",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 1003,
        image: "assets/image6.jpg",
        title: "1BHK Studio in Gaya",
        description: "Affordable studio apartment in Gaya.",
        price: 10000,
        city: "Gaya",
        bhk: "1BHK",
        flatSize: 500,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 30000,
        address: "Bodh Gaya Road, Gaya",
        landmark: "Near Mahabodhi Temple",
        overlooking: "Street",
        developer: "Gaya Builders",
        facing: "West",
        lift: "No"
    },
    {
        id: 1004,
        image: "assets/image9.jpg",
        title: "4BHK Villa in Muzaffarpur",
        description: "Elegant villa with a private garden.",
        price: 85000,
        city: "Muzaffarpur",
        bhk: "4BHK",
        flatSize: 3500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 255000,
        address: "Laxmi Nagar, Muzaffarpur",
        landmark: "Near Laxmi Park",
        overlooking: "Garden",
        developer: "Muzaffarpur Builders",
        facing: "East",
        lift: "No"
    },
    {
        id: 1005,
        image: "assets/image1.jpg",
        title: "2BHK Apartment in Bhagalpur",
        description: "Affordable 2BHK apartment near Bhagalpur Market.",
        price: 18000,
        city: "Bhagalpur",
        bhk: "2BHK",
        flatSize: 900,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 54000,
        address: "Bhagalpur, Bihar",
        landmark: "Near Railway Station",
        overlooking: "Street",
        developer: "Bhagalpur Developers",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 1006,
        image: "assets/image4.jpg",
        title: "3BHK Penthouse in Purnia",
        description: "Luxurious 3BHK penthouse in a quiet area.",
        price: 50000,
        city: "Purnia",
        bhk: "3BHK",
        flatSize: 1800,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "6th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Penthouse",
        securityDeposit: 150000,
        address: "Purnia, Bihar",
        landmark: "Near Purnia College",
        overlooking: "City View",
        developer: "Purnia Developers",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 1007,
        image: "assets/image1.jpg",
        title: "1BHK Flat in Darbhanga",
        description: "Affordable 1BHK flat for singles.",
        price: 12000,
        city: "Darbhanga",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 36000,
        address: "Darbhanga, Bihar",
        landmark: "Near Darbhanga Tower",
        overlooking: "Street",
        developer: "Darbhanga Builders",
        facing: "South",
        lift: "No"
    },

    {
        id: 1101,
        image: "assets/image7.jpg",
        title: "2BHK Flat in Adyar",
        description: "Spacious 2BHK flat in a prime location.",
        price: 35000,
        city: "Chennai",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 105000,
        address: "Adyar, Chennai",
        landmark: "Near Adyar Bridge",
        overlooking: "River View",
        developer: "Adyar Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 1102,
        image: "assets/image1.jpg",
        title: "3BHK Apartment in T Nagar",
        description: "Luxury apartment with modern amenities.",
        price: 60000,
        city: "Chennai",
        bhk: "3BHK",
        flatSize: 1500,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 180000,
        address: "T Nagar, Chennai",
        landmark: "Near Pondy Bazaar",
        overlooking: "City View",
        developer: "T Nagar Constructions",
        facing: "North",
        lift: "Yes"
    },
    {
        id: 1103,
        image: "assets/image10.jpg",
        title: "1BHK Studio in Velachery",
        description: "Modern studio apartment for professionals.",
        price: 22000,
        city: "Chennai",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 66000,
        address: "Velachery, Chennai",
        landmark: "Near Phoenix Mall",
        overlooking: "Street",
        developer: "Velachery Developers",
        facing: "South",
        lift: "No"
    },
    {
        id: 1104,
        image: "assets/image9.jpg",
        title: "4BHK Villa in ECR",
        description: "Luxurious villa with a private pool.",
        price: 150000,
        city: "Chennai",
        bhk: "4BHK",
        flatSize: 4000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "4 Cars",
        type: "Villa",
        securityDeposit: 450000,
        address: "ECR, Chennai",
        landmark: "Near VGP Beach",
        overlooking: "Sea View",
        developer: "ECR Villas",
        facing: "East",
        lift: "No"
    },
    {
        id: 1105,
        image: "assets/image8.jpg",
        title: "2BHK Apartment in OMR",
        description: "Modern 2BHK apartment near IT corridor.",
        price: 40000,
        city: "Chennai",
        bhk: "2BHK",
        flatSize: 1300,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "4th",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 120000,
        address: "OMR, Chennai",
        landmark: "Near Sholinganallur",
        overlooking: "Lake View",
        developer: "OMR Developers",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 1106,
        image: "assets/image1.jpg",
        title: "3BHK Penthouse in Anna Nagar",
        description: "Elegant 3BHK penthouse with city views.",
        price: 85000,
        city: "Chennai",
        bhk: "3BHK",
        flatSize: 2000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "8th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Penthouse",
        securityDeposit: 255000,
        address: "Anna Nagar, Chennai",
        landmark: "Near Tower Park",
        overlooking: "City View",
        developer: "Anna Nagar Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 1107,
        image: "assets/image3.jpg",
        title: "1BHK Flat in Chromepet",
        description: "Affordable 1BHK flat for singles.",
        price: 18000,
        city: "Chennai",
        bhk: "1BHK",
        flatSize: 700,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 54000,
        address: "Chromepet, Chennai",
        landmark: "Near MIT Flyover",
        overlooking: "Street",
        developer: "Chromepet Builders",
        facing: "North",
        lift: "No"
    },

    {
        id: 1201,
        image: "assets/image2.jpg",
        title: "2BHK Flat in Salt Lake",
        description: "Spacious 2BHK flat with modern amenities.",
        price: 30000,
        city: "Kolkata",
        bhk: "2BHK",
        flatSize: 1200,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "3rd",
        balconies: 1,
        carParking: "1 Car",
        type: "Flat",
        securityDeposit: 90000,
        address: "Salt Lake, Kolkata",
        landmark: "Near City Centre Mall",
        overlooking: "Park",
        developer: "Salt Lake Developers",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 1202,
        image: "assets/image5.jpg",
        title: "3BHK Apartment in Ballygunge",
        description: "Luxury apartment in Ballygunge with city views.",
        price: 60000,
        city: "Kolkata",
        bhk: "3BHK",
        flatSize: 1600,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "5th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Apartment",
        securityDeposit: 180000,
        address: "Ballygunge, Kolkata",
        landmark: "Near Ballygunge Lake",
        overlooking: "City View",
        developer: "Ballygunge Builders",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 1203,
        image: "assets/image10.jpg",
        title: "1BHK Studio in New Town",
        description: "Modern studio apartment near IT hub.",
        price: 20000,
        city: "Kolkata",
        bhk: "1BHK",
        flatSize: 600,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "2nd",
        balconies: 1,
        carParking: "No Parking",
        type: "Studio",
        securityDeposit: 60000,
        address: "New Town, Kolkata",
        landmark: "Near Eco Park",
        overlooking: "Street",
        developer: "New Town Developers",
        facing: "North",
        lift: "No"
    },
    {
        id: 1204,
        image: "assets/image9.jpg",
        title: "4BHK Villa in Alipore",
        description: "Luxurious 4BHK villa with a private garden.",
        price: 150000,
        city: "Kolkata",
        bhk: "4BHK",
        flatSize: 3500,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        tenantPreferred: "Family",
        floor: "Ground",
        balconies: 3,
        carParking: "3 Cars",
        type: "Villa",
        securityDeposit: 450000,
        address: "Alipore, Kolkata",
        landmark: "Near Alipore Zoo",
        overlooking: "Garden",
        developer: "Alipore Estates",
        facing: "East",
        lift: "No"
    },
    {
        id: 1205,
        image: "assets/image8.jpg",
        title: "2BHK Apartment in Howrah",
        description: "Comfortable 2BHK apartment near the river.",
        price: 25000,
        city: "Kolkata",
        bhk: "2BHK",
        flatSize: 1000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        tenantPreferred: "Family",
        floor: "2nd",
        balconies: 1,
        carParking: "1 Car",
        type: "Apartment",
        securityDeposit: 75000,
        address: "Howrah, Kolkata",
        landmark: "Near Howrah Bridge",
        overlooking: "River View",
        developer: "Howrah Developers",
        facing: "West",
        lift: "Yes"
    },
    {
        id: 1206,
        image: "assets/image6.jpg",
        title: "3BHK Penthouse in Park Street",
        description: "Exclusive 3BHK penthouse in a vibrant area.",
        price: 80000,
        city: "Kolkata",
        bhk: "3BHK",
        flatSize: 2200,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        tenantPreferred: "Family",
        floor: "7th",
        balconies: 2,
        carParking: "2 Cars",
        type: "Penthouse",
        securityDeposit: 240000,
        address: "Park Street, Kolkata",
        landmark: "Near Park Street Metro",
        overlooking: "City View",
        developer: "Park Street Builders",
        facing: "East",
        lift: "Yes"
    },
    {
        id: 1207,
        image: "assets/image7.jpg",
        title: "1BHK Flat in Dum Dum",
        description: "Affordable 1BHK flat in a quiet area.",
        price: 15000,
        city: "Kolkata",
        bhk: "1BHK",
        flatSize: 550,
        furnishing: "Semi-Furnished",
        bathrooms: 1,
        tenantPreferred: "Bachelors",
        floor: "1st",
        balconies: 1,
        carParking: "No Parking",
        type: "Flat",
        securityDeposit: 45000,
        address: "Dum Dum, Kolkata",
        landmark: "Near Dum Dum Metro",
        overlooking: "Street",
        developer: "Dum Dum Builders",
        facing: "North",
        lift: "No"
    }
]

export default Data;